name: ChuckyGrief
version: 1.0-SNAPSHOT
author: Zen Wolf
main: me.zenisbestwolf.ChuckyGrief.Main
description: Basic grief alert system for the ignChucky SMP server.
api-version: 1.16
permissions:
    chuckygrief.receive:
        description: "Permission to receive broadcasts."
        default: op